version: '2.1'

services:

  # App
  ssh:

    hostname: example.com

    container_name: ssh.example.com

    build:
      context: ./build
      dockerfile: Dockerfile-ssh
      args:
        P_UID: 501
        P_GID: 20
        P_SSH_PASSWORD: foobar         
    
    image: example.com/sshd

    #restart: always
    
    ports:
      - "8822:22"  
      
    volumes:
      - ../www:/www:rw
      
    networks:
      - shared
  
networks:
  shared:
    external:
      name: shared         
